### ISSUE TITLE
Roadmap: chess.js 1.0.0

### ISSUE THREAD

**Issue by jhlywa** [jhlywa/chess.js#319]
After 13 years of pre-1.0.0 development .... it's time.

This is a working document to track planned features/changes and their statuses for version 1.0.0.  Please comment if there's something you'd like to see included or changed. I appreciate and value your feedback.  Check back frequently for updates.

I'll push a basic typescript implementation to **dev** branch to use as starting point. 

~~Please wait for the **dev** branch before submitting PR's.~~

**dev** branch is now active

## Proposed 1.0.0 Changes

- [ ] Code
  - [x] Rewrite library in typescript
  - [x] Use camelcase for API and everything else
    - [x] enforce with eslint rule
  - [x] Use exceptions in error states instead of returning `null`. This will allow the library to provide more detailed error messages for common issues (e.g. bad moves, bad FEN, bad PGN).  The functions that throw exceptions are listed in the API Changes section.
    - [x] throw exception for bad FEN in `.load()` 
    - [x] throw exception for bad FEN  in `Chess()` constructor
    - [x] throw exception for bad PGN in `loadPgn()`
    - [x] throw exception for bad SAN in `move()`
    - [x] throw exception for bad move object in `move()`
  - [x] Switch to using the sloppy FEN/PGN parser by default.  The phrase sloppy is kind of passive aggressive, so maybe use the terms `permissive` and `strict`.
    - [X] `load` in permissive mode (the default mode) should let the user load FEN without supplying castling rights, ep square, and move numbers (e.g. chess.load(`rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w`))
    - [x] `load` and `loadPgn` should allow an option to use the strict parser 
  - [x] `moves()` should work even if there are no kings on the board. 
  - [x] Only set the en passant square when the opponent can legally make an en passant move. (see #294)
  - [x] Add a 'lan' (better name or is this ok??) property for long algebraic notation (see #259)
  - [x] Improve FEN validation.  It should detect common hand-entered such as missing kings and incorrect castling rights. 
  - [ ] Use fast-check for property-based testing
  
- [ ] Docs
  - [ ] create a chess.js logo (maybe this is something the community can vote on??)
  - [ ] Move documentation to chessjs.org 
  - [ ] Add an FAQ section to answer common questions

- [ ] Other
  - [ ] Github issue template ensuring the reporter know the rules of chess before filing a bug  (en passant gets flagged as a bug a few times a year) 
  - [ ] Prefer stackoverflow for chess.js usage questions, github issues for bugs

## API Changes

- [x] `game_over` -> `isGameOver`
- [x] `in_check` -> `isCheck`
- [x] `in_checkmate` -> `isCheckmate`
- [x] `in_draw` -> `isDraw`
- [x] `is_stalemate` -> `isStalemate`
- [x] `in_threefold_repetition` -> `isThreefoldRepetition`
- [x] `insufficient_material` -> `isInsufficientMaterial`
- [x] `load_pgn` -> `loadPgn`
- [x] `set_comment` -> `setComment`
- [x] `get_comment` -> `getComment`
- [x] `get_comments` -> `getComments`
- [x] `delete_comment` -> `deleteComment`
- [x] `delete_comments` -> `deleteComments`
- [x] `validate_fen` -> `validateFen`
- [x] The following functions should throw exceptions in the event of an error
  - [x] `Chess` constructor
  - [x] `load`
  - [x] `loadPgn`
  - [x] `move`

##  Questions
- ~~Should acronyms be capitalized in function names (e.g. `loadPgn` vs `loadPGN`)?  Consider the impact this could have on the `.fen()` and `.pgn()` functions. I'm leaning towards no, but it's up for discussion.~~ Decided not to capitalize acronyns.
-  Should we adopt the chess.js TypeScript definitions from DefinitelyTyped as a basis for our types?

## Future Changes beyond 1.0.0
- use piece lists for increased move generation performance
- use a parser generator to parse PGN
- add support for RAV (recursive annotation variations)
- add support for null moves
- chess960 support

## Issues for First Time Contributors
- add a default separator='\n' parameter to the `ascii()` function

**Comment by coffeeDev98** [comment]
Hey @jhlywa ,
Great to see this is back in development!! Have been using the stable package for our project... 
Had a request... Is it possible to add variations support...? Or Is it something that you're planning to add...? Like in @aaronfi 's project [chess-es6](https://github.com/jhlywa/chess.js)

**Comment by jhlywa** [comment]
The variation code will most likely come later in version 2.0.0 (I refer to it above as RAV - Recursive Annotation Variation). The PGN loading code needs to be rewritten from the ground up.  It's currently a set of hand crafted rules that are a little tedious to maintain and follow. A better approach would be to include the PGN grammar and then use a parser generator to generate the parsing code.  Once this is done, dding support for variations should be significantly easier.

**Comment by coffeeDev98** [comment]
Hey @jhlywa,
Had a doubt... How would you go about with creating the PEG file / Grammar file? Will you be creating one from scratch or referring to an existing one like, PGNViewer...? Looking into the PGN Grammar right now..

**Comment by DevAndrewGeorge** [comment]
Just began using this repo, but this is exciting! I'll happily make some contributions once the FIX_ME branch is live.

**Comment by jhlywa** [comment]
@coffeeDev98 I'd be interesting in creating the grammar from scratch. I think it would give us a better understanding of how the  PGN parser works, and frankly, I think it would be easier than maintaining the existing regexes.

**Comment by jhlywa** [comment]
Hi all, I just pushed the new **dev** branch this morning.  I manually copied over all of the tests from the 0.13.2 tag and added a few extras where necessary.  However, there does seems to be a discrepancy in the number of tests cases jest is running in 0.13.2 (339 test cases) and dev (237 cases).  We should investigate this.

**Comment by coffeeDev98** [comment]
I shall do a deep dive of the code before contributing... Any advice on the same...? I'm new to contributions on github... 😅

**Comment by DevAndrewGeorge** [comment]
@jhlywa, did you ever resolve the test issue? I don't see as big of a discrepancy between `v013.2` and `dev` as you state:
```
Andrews-MacBook-Pro:chess.js andrew$ git checkout v0.13.2; npm test 2>&1 | grep "Tests:"
HEAD is now at 426e7ed 0.13.2
Tests:       338 passed, 338 total
Andrews-MacBook-Pro:chess.js andrew$ git checkout master; npm test 2>&1 | grep "Tests:"
Previous HEAD position was 426e7ed 0.13.2
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Tests:       339 passed, 339 total
```

**Comment by jhlywa** [comment]
Hi @DevAndrewGeorge. No, I haven't been able to account for the discrepancy in tests cases.  I did omit a few cases that I though were redundant on the `dev` branch, and also refactored a few others. I expected to be within 10-20 tests cases of v0.13.2, but running your snippet on `dev` shows we're missing about 100 cases.  (BTW - I think you ran on the wrong branch, be sure you're on `dev`  when generating a test count)

```
$ git checkout dev && npm test 2>&1 | grep "Tests:"
Tests:       237 passed, 237 total
```

**Comment by DevAndrewGeorge** [comment]
Ah, good catch. The main source of your discrepancy is that the `validate_fen.test.ts` file ran all cases in a single test. See #333 where I've "fixed" this in by running each case individually.

**Comment by LandonSchropp** [comment]
@jhlywa Would it be possible to request an alpha NPM release of this? I'm using this for a side project, so I don't mind if things aren't 100% right now, but I would like to use this project in CI, and it's a bit tricky right now with the current flow of manually building the package.

**Comment by LandonSchropp** [comment]
Also, if there's a major version bump coming anyway, can I suggest the accessor functions that take no arguments be converted to properties? For example:

``` js
fen() {
   .
}
```

Could become:

``` js
get fen() {
  ...
}
```

**Comment by LandonSchropp** [comment]
Another request:

For the `history` function, it would be really handy if each value in history included the `fen` at that point in the time.

**Comment by SheetJSDev** [comment]
> Improve FEN validation. It should detect common hand-entered such as missing kings and incorrect castling rights.

If missing kings is considered invalid, extra kings should also be considered invalid.  `kkkkkkkk/8/8/8/8/8/8/KKKKKKKK w KQkq - 0 1` is an example board discussed in issue #289

**Comment by will-lamerton** [comment]
Wicked stuff! Using Chess.js in our Chess engine! Gave the package credit for move generation and game state detection on the website and the in the docs :)

**Comment by vicary** [comment]
Never capitalize abbv, they tend to mess with other things.

**Comment by jhlywa** [comment]
Hi all. The latest beta has been pushed to NPM. I have one more planned code change (adding a `before` and `after` FEN field to to verbose history output). Here are the release notes:
 
https://github.com/jhlywa/chess.js/releases/tag/v1.0.0-beta.0

**Comment by SheetJSDev** [comment]
There's a packaging issue with the beta:

```
npm ERR! command failed
npm ERR! command sh -c -- npm run build
npm ERR! > chess.js@1.0.0-beta.0 build
npm ERR! > tsc --build
npm ERR! sh: tsc: command not found
```

It looks like the module ships with the typescript code (`src/chess.ts`) as well as the JS code (`dist/chess.js` and types file) but also has a postinstall step that runs `tsc`.  Since `main` points to the JS file in the `dist` folder, is that post-install step necessary?

**Comment by jhlywa** [comment]
@SheetJSDev Doh! Thanks for the feedback. A fix tagged 1.0.0-beta.1 has been published.

**Comment by qwerty084** [comment]
> Hi all. The latest beta has been pushed to NPM. I have one more planned code change (adding a `before` and `after` FEN field to to verbose history output). Here are the release notes:
> 
> https://github.com/jhlywa/chess.js/releases/tag/v1.0.0-beta.0

This change would be really nice, having before and after fen :)

**Comment by jhlywa** [comment]
@qwerty084 `before` and `after` have been added to the `Move` object returned by `.move()`, `.undo`,  `.moves()`, and `.history()`. The two latter methods need to be called with `{ verbose: true }` to return `Move[]`.

It's been pushed to npm as 1.0.0-beta.4

**Comment by arthurchumak** [comment]
🥺 waiting for chess 960 support https://github.com/jhlywa/chess.js/issues/122

**Comment by ppeloton** [comment]
I am interested in the support for null moves and I have already made some thoughts how to implement such a feature to this package. Before I provide a pull request, have there been any thoughts on the SAN of a null move. There is no standard SAN representation for a null move. I would suggest "--" but there are others (see e.g. https://chess.stackexchange.com/questions/14072/san-for-nullmove )

**Comment by jhlywa** [comment]
Hi @ppeloton. The lack of a standard is why we traditionally didn't support null moves. However, with switch to the permissive SAN parser, I think it's time we add it. I think it's reasonable to start with "--" as the SAN representation of a null move.

**Comment by cmgchess** [comment]
looking forward 960 support!

**Comment by jhlywa** [comment]
v1.0.0 has been pushed to NPM. Enjoy!
